### ISSUE TITLE
How to add SRT over RTMP

### ISSUE THREAD

**Issue by wangpeng1** [ThibaultBee/srtdroid#25]
Hi，My program already has rtmp, I want to add srt to this project，Whether this library can meet the needs, or need to use StreamPack？ thank you

**Comment by ThibaultBee** [comment]
Hi,

The technical choices are up to you.

As it might be clear, here is a quick definition of the libs:
- srtdroid is a low level wrapper around libsrt for SRT connection. It is kind of like Socket API (but with SRT instead of TCP/UDP).
- StreamPack captures your camera and microphones, encodes, muxes and sends the packet to a remote server (SRT or RTMP). Internally StreamPack uses srtdroid.
